### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by KuroiKitsu** [tenchoufansubs/lolicon#2]
Kudos are a way to reward ~~ourselves~~ users for contributing to the fansub. It's just a number (like the *exp* in RPGs), but it might be interesting.

For example, assuming the command prefix is `!`, this should give kudos to the user `@Someone`

```
!kudos @Someone
```

The amount of kudos for the current user could be retrieved by mentioning the bot (`@Lolicon`) like this:

```
@Lolicon kudos
```

**Comment by noisypixy** [comment]
This has been implemented in [go-lolicon](https://github.com/tenchoufansubs/go-lolicon).
