### ISSUE TITLE
Japanese dictionary

### ISSUE THREAD

**Issue by KuroiKitsu** [tenchoufansubs/lolicon#3]
When translating Ajin we needed to look up some Japanese words, so this feature could be handy sometime in the future.

For example, assuming `!` is the command prefix, one could look up the meaning of a Japanese term like this:

```
!translate 教室
```

The command name (`translate`) is subject to change.

---

This feature could be implemented by querying other sites like [Tanoshii Japanese](http://www.tanoshiijapanese.com/home/).

**Comment by noisypixy** [comment]
Implemented into [go-lolicon](https://github.com/tenchoufansubs/go-lolicon) using <http://jisho.org/>.
